name: CI - Test Weather ETL Package with Anaconda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          auto-update-conda: true
          activate-environment: weather-etl-py${{ matrix.python-version }}
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Cache Conda packages
        uses: actions/cache@v3
        env:
          CONDA_PKGS_DIR: /usr/share/conda/pkgs
        with:
          path: ${{ env.CONDA_PKGS_DIR }}
          key: conda-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-${{ runner.os }}-py${{ matrix.python-version }}-

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install -n weather-etl-py${{ matrix.python-version }} pytest
          conda list

      - name: Install package in editable mode
        shell: bash -l {0}
        run: pip install --no-cache-dir -e .

      - name: Run tests
        shell: bash -l {0}
        run: pytest -v --cov=your_package_name --cov-report=xml
