name: CI - Test Weather ETL Package with Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: weather-etl-env
          auto-update-conda: true
          # Disable package cache configuration to avoid the cancellation error.
          conda-cache: false

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run tests
        run: pytest
