name: CI - Test Weather ETL Package with Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]  # Specify the Python versions to test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          # Name of the environment to create/activate
          activate-environment: weather-etl-env
          auto-update-conda: true
          # If you have an environment.yml in the repo, it will be used to create the environment.
          # Remove or comment out the next line if you want to install dependencies manually.
          environment-file: environment.yml

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run tests
        run: pytest
