- name: Verify package structure
  run: |
    if [ ! -f "setup.py" ] && [ ! -f "pyproject.toml" ]; then
      echo "Error: Missing package configuration file (setup.py or pyproject.toml)"
      exit 1
    fi

- name: Install dependencies
  shell: bash -l {0}
  run: |
    conda install --quiet --yes pip
    pip install --no-cache-dir -e .[test]
